{ cfg, ... }:
{
  packages = {
    flutter-init =
      pkgs:
      pkgs.writeShellApplication {
        name = "flutter-init";
        runtimeInputs = with pkgs; [
          bash
          flutter327
        ];
        text = ''
          #!/usr/bin/env bash
          # 1) Create flutter initial project files
          flutter create .
          # 2) Update compileSdkVersion
          gradle_file="./android/app/build.gradle"
          cp "$gradle_file" "$gradle_file.bak"
          sed -i.bak 's/flutter\.compileSdkVersion/${cfg.compileSdkVersion}/g' "$gradle_file"
          echo "✅ Updated compileSdkVersion reference in $gradle_file" to ${cfg.compileSdkVersion}
          # 3) add local.properties to ./anddroid/ folder
          # TODO consder referencing the nix packages instead of shell env vars
          # cat <<EOF > ./android/local.properties
          # This file was automatically generated by nix-shell.
          # sdk.dir=$ANDROID_HOME
          # ndk.dir=$ANDROID_NDK_ROOT
          # flutter.sdk=$FLUTTER_ROOT
          # EOF
        '';
      };
  };
}
